services:
  # MinIO
  minio:
    image: minio/minio:RELEASE.2024-06-11T03-13-30Z
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: unless-stopped

  # Jupyter + Spark
  pyspark:
    build:
      context: .
      dockerfile: Dockerfile   # aqui você define explicitamente o Dockerfile padrão do jupyter
    container_name: pyspark
    environment:
      JUPYTER_TOKEN: "minhasenha"
    ports:
      - "8888:8888"
    depends_on:
      - minio
    volumes:
      - ./notebooks:/home/jovyan/work

  # MongoDB
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    restart: unless-stopped

  # Ambiente Python customizado
  python-env:
    build:
      context: .
      dockerfile: Dockerfile-py   # aqui você força usar o Dockerfile_py
    container_name: python-env
    volumes:
      - ./src:/app/src
    stdin_open: true
    tty: true

volumes:
  minio_data:
  mongo_data:
